{"uuid": "6b213fba-1d4a-44d6-97d2-9af16ff71603", "children": ["b71febe0-09a6-4887-8bb6-9c6840da3fdc"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59171): Max retries exceeded with url: /session/34c2e99428a5658909450eba6a420beb/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d804390>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/_pytest/python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/_pytest/python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/liyufang/Desktop/code/cmp-test/cmp-test/cmp_test/testcase/ui/base.py\", line 9, in setup_class\n    cls.client.connect()\n  File \"/Users/liyufang/Desktop/code/cmp-test/cmp-test/cmp_test/lib/ui/client.py\", line 33, in connect\n    self.browser.implicitly_wait(5)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 912, in implicitly_wait\n    'implicit': int(float(time_to_wait) * 1000)})\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/request.py\", line 79, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/Users/liyufang/Desktop/code/cmp-test/venv/lib/python3.7/site-packages/urllib3/util/retry.py\", line 573, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1610369070370, "stop": 1610369070384}], "start": 1610369070370, "stop": 1610369070938}